name: Build & deploy Jupyter Book

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

env:
  # BASE_URL determines where the website is served from, including CSS & JS assets
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write           # for GitHub Pages
  id-token: write        # for OIDC auth

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Build the book
        run: |
          set -e
          jupyter book build --html || jupyter-book build --html
          [ -d "_build/site" ] && cp -r _build/site _build/html || [ -d "_build/html" ]

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
